# Generated by Django 4.2 on 2023-04-09 23:17
from django.contrib.gis.geos import Point
from django.db import migrations
from ..data import data as vehicles


def load(apps, _):
    # noinspection PyPep8Naming
    Vehicle = apps.get_model('vehicles', 'Vehicle')
    result = []
    for vehicle in vehicles:
        _, license_plate, battery_level, in_use, model, (lat, lon) = vehicle.values()
        result.append(Vehicle(
            license_plate=license_plate,
            battery_level=battery_level,
            in_use=in_use,
            model=model,
            location=Point(float(lat), float(lon))
        ))

    Vehicle.objects.bulk_create(result)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load)
    ]
