# Generated by Django 4.2 on 2023-04-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_shift_swap'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='swap',
            index=models.Index(fields=['shift_id', 'vehicle_id'], name='search_shift_vehicle'),
        ),
    ]
